services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/app/pb_data

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
